/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ep Digital Design (https://sketchfab.com/Epdigitaldesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wireframe-3d-globe-20adb20e73ee4b68bc1207e1675b8891
Title: Wireframe 3D Globe
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {useFrame} from "@react-three/fiber";

function Globe({ color, ...props }) {
    const { nodes } = useGLTF("/models/scene.gltf");

    /*const groupRef = useRef();

    useFrame((_, delta) => {
      groupRef.current.rotation.z += delta * 0.3;
      groupRef.current.rotation.x += delta * 0.1;
    }); */

    return (
      <group /*ref={groupRef}*/ {...props}>
        <mesh geometry={nodes.Object_2.geometry}>
            <meshStandardMaterial
                emissive={color}
                emissiveIntensity={0.55}
            />
        </mesh>
      </group>
    );
}

useGLTF.preload('/models/scene.gltf')

export default Globe